### ISSUE TITLE
Skipped line 6558 (java.lang.NumberFormatException: For input string: "2099/01/22 23:59:59"):

### ISSUE THREAD

**Issue by fs-rd-anish-dey** [hiroyuki-sato/embulk-support#2]
Hello,
For String column embulk cannot parse a specific kind of string "2099/01/22 23:59:59".
Has anyone encountered this before?
Any help will be greatly appreciated

**Comment by hiroyuki-sato** [comment]
Hello, @fs-rd-anish-dey 

Can you write your question on the https://github.com/embulk/embulk?
And can you show us your input data and configuration (except password etc.)
What embulk version are you used?

This repository is my personal use only.

**Comment by hiroyuki-sato** [comment]
The following sample data of the third field is `2099/01/22 23:59:59`.
Using the following configuration, Embulk read it as string data.

I suppose your configuration set column type `double` or `long` instead of `string`.

```csv
id,account,time,purchase,comment
1,32864,2099/01/22 23:59:59,20150127,embulk
2,14824,2099/01/22 23:59:59,20150127,embulk jruby
3,27559,2099/01/22 23:59:59,20150128,"Embulk ""csv"" parser plugin"
4,11270,2099/01/22 23:59:59,20150129,NULL
```


```yaml
in:
  type: file
  path_prefix: /private/tmp/foo/csv/sample_
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: string, format: '%Y/%m/%d %H:%M:%S'}  # <-- HERE
    - {name: purchase, type: string, format: '%Y%m%d'}
    - {name: comment, type: string}
out: {type: stdout}
```

**Comment by fs-rd-anish-dey** [comment]
Hello Sato-san

Thank you for your quick response.
Actually my data had a lot of tabs in fields,some of them were trailing which led to the columns being read/parsed in different order from the yml configuration.Also when I changed all columns to **string** then [Too Many Columns] warning was shown which led me to double check my data.
I changed my data so that each field is enclosed in quotes and the yml had the following config.
Then the data was parsed by embulk.
```
parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: "\t"
    quote: '"'
    escape: '\'
    trim_if_not_quoted: false
    skip_header_lines: 0
    allow_extra_columns: false
    allow_optional_columns: false
```
